#!/usr/bin/env bash
set -euo pipefail

# Point `mtplx` at THIS checkout's venv, so local edits are what actually runs.
# Sister script to install_macos.sh (which installs the PyPI wheel); unlike that
# one, this never touches a downloaded runtime and never overwrites your work.
#
# A checkout that moved is the case this script exists for. Three layers bake the
# absolute repo path -- the launcher it execs, the venv console script, and the
# editable-install finder in site-packages -- and the last two are uv's metadata,
# so the repair is `uv sync`, not sed.

launcher_marker="MTPLX launcher. Generated by scripts/install_repo_launcher.sh."
alias_line='alias mtplx="$HOME/.mtplx/bin/mtplx"'

usage() {
  cat <<'EOF'
Usage:
  scripts/install_repo_launcher.sh [--force] [--no-sync] [--check]

Creates <MTPLX_HOME>/bin/mtplx launching this checkout's .venv and adds an
`mtplx` alias to the login shell's rc file (~/.zshrc for zsh, ~/.bashrc for
bash). Every step is idempotent.

  --force    replace the launcher even if it exists, including a hand-written one
  --no-sync  report a venv that does not serve this checkout instead of running uv
  --check    read-only drift report; exit 1 if anything needs action, write nothing

The rc step is two lines, each added only if it is not already there: a PATH
entry that puts the launcher's bin dir in FRONT (an append-style entry can still
lose to a Homebrew mtplx), and an `mtplx` alias.

When the venv is unusable for this checkout -- absent, or importing mtplx from
somewhere else, which is what a moved repo does -- `uv sync` runs here and the
launcher is rewritten. mlx is printed before and after so a pin regression is
visible rather than silent.
EOF
}

force=0
no_sync=0
check_only=0
for arg in "$@"; do
  case "$arg" in
    -h|--help) usage; exit 0 ;;
    --force) force=1 ;;
    --no-sync) no_sync=1 ;;
    --check) check_only=1 ;;
    *) printf 'unknown argument: %s\n' "$arg" >&2; usage >&2; exit 2 ;;
  esac
done

repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
bin_dir="${MTPLX_HOME:-$HOME/.mtplx}/bin"
launcher="$bin_dir/mtplx"
venv_mtplx="$repo/.venv/bin/mtplx"
venv_python="$repo/.venv/bin/python3"
drift=0

# The editable install stores an absolute path, so a moved checkout can still
# import mtplx from where it was installed. Healthy means all three: the console
# script runs, its shebang interpreter exists, and the import resolves inside
# this checkout. -P matters: without it python prepends the caller's cwd, so
# running this from inside the repo would resolve mtplx from cwd and bless a venv
# whose editable install still points at an old path.
venv_serves_repo() {
  [ -x "$venv_mtplx" ] || return 1
  [ -x "$venv_python" ] || return 1
  local interp
  interp=$(sed -n '1s|^#!\([^ ]*\).*|\1|p' "$venv_mtplx")
  if [ -n "$interp" ] && [ ! -x "$interp" ]; then
    return 1
  fi
  REPO="$repo" "$venv_python" -P -c '
import os, sys
import mtplx
here = os.path.realpath(os.environ["REPO"])
sys.exit(0 if os.path.realpath(mtplx.__file__).startswith(here + os.sep) else 1)
' >/dev/null 2>&1
}

mlx_version() {
  if [ -x "$venv_python" ]; then
    "$venv_python" -P -c 'import mlx.core as m; print(m.__version__)' 2>/dev/null || printf 'unknown\n'
  else
    printf 'none\n'
  fi
}

run_uv_sync() {
  if ! command -v uv >/dev/null 2>&1; then
    printf 'the venv needs a sync but `uv` is not on PATH\n' >&2
    printf 'install uv, or do it by hand: cd %s && uv sync\n' "$repo" >&2
    exit 1
  fi
  printf 'venv does not serve this checkout -- running: (cd %s && uv sync)\n' "$repo"
  printf 'any server already serving from this venv needs a restart afterwards\n'
  printf 'mlx before: %s\n' "$(mlx_version)"
  if ! ( cd "$repo" && uv sync ); then
    printf 'uv sync failed; nothing was pointed at this checkout\n' >&2
    exit 1
  fi
  printf 'mlx after:  %s\n' "$(mlx_version)"
}

write_launcher() {
  mkdir -p -- "$bin_dir"
  tmp="$launcher.$$.tmp"
  {
    printf '#!/bin/sh\n'
    printf '# %s\n' "$launcher_marker"
    printf '# repo: %s\n' "$repo"
    printf '# Rollback: exec the app runtime instead, see ~/.mtplx/tasks/issue-2-*.md\n'
    printf 'export PYTHONPYCACHEPREFIX=%s\n' "'$HOME/Library/Caches/MTPLX/PythonBytecode'"
    printf 'exec %s "$@"\n' "'$venv_mtplx'"
  } > "$tmp"
  chmod +x "$tmp"
  mv "$tmp" "$launcher"
  printf 'launcher: wrote %s\n' "$launcher"
}

# --- 1. the venv has to be usable before anything points at it --------------
if venv_serves_repo; then
  printf 'venv: serves %s\n' "$repo"
else
  drift=1
  if [ "$check_only" = 1 ]; then
    printf 'venv: needs uv sync (absent, or mtplx imports from another path)\n'
  elif [ "$no_sync" = 1 ]; then
    printf 'venv: does not serve %s and --no-sync was given\n' "$repo" >&2
    printf 'fix it by hand: cd %s && uv sync\n' "$repo" >&2
    exit 1
  else
    run_uv_sync
    if ! venv_serves_repo; then
      printf 'after uv sync, mtplx still does not import from %s\n' "$repo" >&2
      exit 1
    fi
    printf 'venv: repaired, serves %s\n' "$repo"
  fi
fi

# --- 2. the launcher, with provenance so a moved checkout is visible --------
recorded=""
if [ -f "$launcher" ]; then
  recorded=$(awk '/^# repo: /{sub(/^# repo: */,""); print; exit}' "$launcher")
fi

if [ ! -e "$launcher" ]; then
  drift=1
  if [ "$check_only" = 1 ]; then
    printf 'launcher: absent, would create %s\n' "$launcher"
  else
    write_launcher
  fi
elif [ "$force" = 1 ]; then
  drift=1
  if [ "$check_only" = 1 ]; then
    printf 'launcher: --force given, would rewrite %s\n' "$launcher"
  else
    write_launcher
  fi
elif ! grep -qF "$launcher_marker" "$launcher"; then
  target=$(awk '/^exec /{print $2; exit}' "$launcher" | tr -d "'")
  printf 'launcher: one you wrote by hand is at %s -- leaving it as is\n' "$launcher"
  printf '          it execs: %s\n' "${target:-nothing recognisable}"
  if [ -n "$target" ] && [ ! -x "$target" ]; then
    drift=1
    printf '          that target no longer exists -- rerun with --force to take it over\n'
  else
    printf '          rerun with --force to replace it with the generated one\n'
  fi
elif [ "$recorded" = "$repo" ]; then
  printf 'launcher: already installed for this checkout at %s\n' "$launcher"
elif [ -n "$recorded" ] && [ -d "$recorded" ]; then
  drift=1
  printf 'launcher: points at a different checkout, and both still exist\n'
  printf '          installed: %s\n' "$recorded"
  printf '          this one:  %s\n' "$repo"
  printf '          nothing was guessed -- rerun with --force to repoint it here\n'
else
  drift=1
  printf 'launcher: stale, generated for %s, which no longer exists\n' "${recorded:-no # repo: line}"
  if [ "$check_only" = 1 ]; then
    printf '          --check: would repoint it at %s\n' "$repo"
  else
    write_launcher
    printf '          repointed at %s\n' "$repo"
  fi
fi

# --- 3. the alias -----------------------------------------------------------
shell_name=""
if command -v dscl >/dev/null 2>&1; then
  shell_name=$(basename "$(dscl . -read "/Users/$USER" UserShell 2>/dev/null | awk '{print $2}')" 2>/dev/null || true)
fi
[ -n "$shell_name" ] || shell_name=$(basename "${SHELL:-sh}")
case "$shell_name" in
  zsh) rc="${MTPLX_RC:-$HOME/.zshrc}" ;;
  bash) rc="${MTPLX_RC:-$HOME/.bashrc}" ;;
  *) rc="${MTPLX_RC:-$HOME/.profile}" ;;
esac
printf 'login shell: %s -> %s\n' "$shell_name" "$rc"

# --- PATH: the entry must be IN FRONT, not merely present -------------------
# Three `mtplx` binaries exist on a machine like this one (repo, a Homebrew
# 2.7.1, the app runtime-venv). A line like PATH="$PATH:$HOME/.mtplx/bin" would
# satisfy "the dir is on PATH" and still lose to Homebrew, so the position is
# part of the check. Commented-out lines do not count.
path_needle=""
path_is_home=0
case "$bin_dir" in
  "$HOME"/*) path_needle="${bin_dir#"$HOME"/}"; path_is_home=1 ;;
  *) path_needle="$bin_dir"; path_is_home=0 ;;
esac
path_lineno=""
path_line=""
if [ -f "$rc" ]; then
  path_lineno=$(awk -v e="$path_needle" '
    { line=$0; sub(/^[ \t]+/, "", line) }
    substr(line, 1, 1) == "#" { next }
    index(line, "export PATH=") && index(line, e) { print NR; exit }
  ' "$rc")
fi
path_state=absent
path_owner=""
if [ -n "$path_lineno" ]; then
  path_line=$(awk -v n="$path_lineno" 'NR==n' "$rc")
  path_owner=$(awk -v n="$path_lineno" 'NR==n-1 && /^#/' "$rc")
  rest=${path_line#*"$path_needle"}
  case "$rest" in
    ':$PATH'*) path_state=front ;;
    *) path_state=behind ;;
  esac
fi

if [ "$path_is_home" = 1 ]; then
  path_want="export PATH=\"\$HOME/$path_needle:\$PATH\""
else
  path_want="export PATH=\"$bin_dir:\$PATH\""
fi

append_rc_line() {
  if ! grep -qF '# Added by scripts/install_repo_launcher.sh' "$rc"; then
    printf '\n# Added by scripts/install_repo_launcher.sh\n' >> "$rc"
  fi
  printf '%s\n' "$1" >> "$rc"
}

case "$path_state" in
  front)
    printf 'PATH: %s in front (%s:%s)\n' "$path_needle" "$rc" "$path_lineno"
    if [ -n "$path_owner" ]; then
      printf '      written by: %s\n' "$path_owner"
    fi
    ;;
  behind)
    drift=1
    printf 'PATH: %s is on PATH but NOT in front (%s:%s)\n' "$path_needle" "$rc" "$path_lineno"
    printf '      found: %s\n' "$path_line"
    printf '      something earlier on PATH can win `mtplx`; the front form gets added below\n'
    if [ "$check_only" = 0 ]; then
      append_rc_line "$path_want"
      printf 'PATH: added %s\n' "$path_want"
    fi
    ;;
  absent)
    drift=1
    if [ "$check_only" = 1 ]; then
      printf 'PATH: no %s entry in %s\n' "$path_needle" "$rc"
    else
      append_rc_line "$path_want"
      printf 'PATH: added %s\n' "$path_want"
    fi
    ;;
esac

# What the login shell actually runs is the only honest oracle: the rc text can be
# present and correct and still lose to an earlier PATH entry. Interactive startup
# prints banners (gitstatus alone emits 13 lines here), so take the last line that
# looks like an mtplx path, and never let a slow or hanging rc affect the result.
if [ "${MTPLX_NO_SHELL_PROBE:-0}" != 1 ]; then
  probe_bin="$shell_name"
  if [ -n "${MTPLX_LOGIN_SHELL:-}" ]; then
    probe_bin="$MTPLX_LOGIN_SHELL"
  fi
  if command -v "$probe_bin" >/dev/null 2>&1; then
    # `|| true`: under set -euo pipefail a pipeline whose grep finds nothing returns
    # 1, which would abort the whole script on an inconclusive probe.
    resolved=$(timeout 12 "$probe_bin" -lic 'command -v mtplx' 2>/dev/null | grep -E '/mtplx$' | tail -1) || true
    if [ -z "$resolved" ]; then
      printf 'shell probe: %s did not resolve `mtplx` (rc noise, timeout, or not on PATH)\n' "$shell_name"
    elif [ "$resolved" = "$launcher" ]; then
      printf 'shell probe: %s runs %s\n' "$shell_name" "$resolved"
    else
      drift=1
      printf 'shell probe: %s runs %s -- NOT %s\n' "$shell_name" "$resolved" "$launcher"
      printf '           a PATH entry ahead of this one wins, so the launcher above is not what you execute\n'
    fi
  fi
fi

if [ "$check_only" = 1 ]; then
  if grep -qE '^alias mtplx=' "$rc" 2>/dev/null; then
    echo "The alias already exists"
  else
    drift=1
    printf 'alias: missing from %s\n' "$rc"
  fi
else
  if [ ! -f "$rc" ] && ! touch -- "$rc" 2>/dev/null; then
    printf 'cannot write %s -- skipping the alias\n' "$rc" >&2
    exit 1
  fi
  if grep -qE '^alias mtplx=' "$rc"; then
    echo "The alias already exists"
    grep -nE '^alias mtplx=' "$rc" | head -1
  else
    append_rc_line "$alias_line"
    printf 'alias: added to %s\n' "$rc"
    printf 'activate it: source %s\n' "$rc"
  fi
fi

if [ "$check_only" = 1 ]; then
  if [ "$drift" = 1 ]; then
    printf '\n--check: drift found, nothing written\n'
    exit 1
  fi
  printf '\n--check: aligned, nothing written\n'
  exit 0
fi

printf '\nverify: %s status | head -3   (python: should be %s)\n' "$launcher" "$venv_python"
