#!/usr/bin/env bash
set -euo pipefail

# Point `mtplx` at THIS checkout's venv, so local edits are what actually runs.
# Sister script to install_macos.sh (which installs the PyPI wheel); unlike that
# one, this never touches a downloaded runtime and never overwrites your work.
#
# A checkout that moved is the case this script exists for. Three layers bake the
# absolute repo path -- the launcher it execs, the venv console script, and the
# editable-install finder in site-packages -- and the last two are uv's metadata,
# so the repair is `uv sync`, not sed.

launcher_marker="MTPLX launcher. Generated by scripts/install_repo_launcher.sh."
alias_line='alias mtplx="$HOME/.mtplx/bin/mtplx"'

usage() {
  cat <<'EOF'
Usage:
  scripts/install_repo_launcher.sh [--force] [--no-sync] [--check]

Creates <MTPLX_HOME>/bin/mtplx launching this checkout's .venv and adds an
`mtplx` alias to the login shell's rc file (~/.zshrc for zsh, ~/.bashrc for
bash). Every step is idempotent.

  --force    replace the launcher even if it exists, including a hand-written one
  --no-sync  report a venv that does not serve this checkout instead of running uv
  --check    read-only drift report; exit 1 if anything needs action, write nothing

The rc step is two lines, each added only if it is not already there: a PATH
entry that puts the launcher's bin dir in FRONT (an append-style entry can still
lose to a Homebrew mtplx), and an `mtplx` alias.

When the venv is unusable for this checkout -- absent, or importing mtplx from
somewhere else, which is what a moved repo does -- `uv sync` runs here and the
launcher is rewritten. mlx is printed before and after so a pin regression is
visible rather than silent.
EOF
}

force=0
no_sync=0
check_only=0
for arg in "$@"; do
  case "$arg" in
    -h|--help) usage; exit 0 ;;
    --force) force=1 ;;
    --no-sync) no_sync=1 ;;
    --check) check_only=1 ;;
    *) printf 'unknown argument: %s\n' "$arg" >&2; usage >&2; exit 2 ;;
  esac
done

repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
bin_dir="${MTPLX_HOME:-$HOME/.mtplx}/bin"
launcher="$bin_dir/mtplx"
venv_mtplx="$repo/.venv/bin/mtplx"
venv_python="$repo/.venv/bin/python3"
drift=0

# The editable install stores an absolute path, so a moved checkout can still
# import mtplx from where it was installed. Healthy means all three: the console
# script runs, its shebang interpreter exists, and the import resolves inside
# this checkout. -P matters: without it python prepends the caller's cwd, so
# running this from inside the repo would resolve mtplx from cwd and bless a venv
# whose editable install still points at an old path.
venv_serves_repo() {
  [ -x "$venv_mtplx" ] || return 1
  [ -x "$venv_python" ] || return 1
  local interp
  interp=$(sed -n '1s|^#!\([^ ]*\).*|\1|p' "$venv_mtplx")
  if [ -n "$interp" ] && [ ! -x "$interp" ]; then
    return 1
  fi
  REPO="$repo" "$venv_python" -P -c '
import os, sys
import mtplx
here = os.path.realpath(os.environ["REPO"])
sys.exit(0 if os.path.realpath(mtplx.__file__).startswith(here + os.sep) else 1)
' >/dev/null 2>&1
}

mlx_version() {
  if [ -x "$venv_python" ]; then
    "$venv_python" -P -c 'import mlx.core as m; print(m.__version__)' 2>/dev/null || printf 'unknown\n'
  else
    printf 'none\n'
  fi
}

run_uv_sync() {
  if ! command -v uv >/dev/null 2>&1; then
    printf 'the venv needs a sync but `uv` is not on PATH\n' >&2
    printf 'install uv, or do it by hand: cd %s && uv sync\n' "$repo" >&2
    exit 1
  fi
  printf 'venv does not serve this checkout -- running: (cd %s && uv sync)\n' "$repo"
  printf 'any server already serving from this venv needs a restart afterwards\n'
  printf 'mlx before: %s\n' "$(mlx_version)"
  if ! ( cd "$repo" && uv sync ); then
    printf 'uv sync failed; nothing was pointed at this checkout\n' >&2
    exit 1
  fi
  printf 'mlx after:  %s\n' "$(mlx_version)"
}

write_launcher() {
  mkdir -p -- "$bin_dir"
  tmp="$launcher.$$.tmp"
  {
    printf '#!/bin/sh\n'
    printf '# %s\n' "$launcher_marker"
    printf '# repo: %s\n' "$repo"
    printf '# Rollback: exec the app runtime instead, see ~/.mtplx/tasks/issue-2-*.md\n'
    printf 'export PYTHONPYCACHEPREFIX=%s\n' "'$HOME/Library/Caches/MTPLX/PythonBytecode'"
    printf 'exec %s "$@"\n' "'$venv_mtplx'"
  } > "$tmp"
  chmod +x "$tmp"
  mv "$tmp" "$launcher"
  printf 'launcher: wrote %s\n' "$launcher"
}

# --- 1. the venv has to be usable before anything points at it --------------
if venv_serves_repo; then
  printf 'venv: serves %s\n' "$repo"
else
  drift=1
  if [ "$check_only" = 1 ]; then
    printf 'venv: needs uv sync (absent, or mtplx imports from another path)\n'
  elif [ "$no_sync" = 1 ]; then
    printf 'venv: does not serve %s and --no-sync was given\n' "$repo" >&2
    printf 'fix it by hand: cd %s && uv sync\n' "$repo" >&2
    exit 1
  else
    run_uv_sync
    if ! venv_serves_repo; then
      printf 'after uv sync, mtplx still does not import from %s\n' "$repo" >&2
      exit 1
    fi
    printf 'venv: repaired, serves %s\n' "$repo"
  fi
fi

# --- 2. the launcher, with provenance so a moved checkout is visible --------
recorded=""
if [ -f "$launcher" ]; then
  recorded=$(awk '/^# repo: /{sub(/^# repo: */,""); print; exit}' "$launcher")
fi

if [ ! -e "$launcher" ]; then
  drift=1
  if [ "$check_only" = 1 ]; then
    printf 'launcher: absent, would create %s\n' "$launcher"
  else
    write_launcher
  fi
elif [ "$force" = 1 ]; then
  drift=1
  if [ "$check_only" = 1 ]; then
    printf 'launcher: --force given, would rewrite %s\n' "$launcher"
  else
    write_launcher
  fi
elif ! grep -qF "$launcher_marker" "$launcher"; then
  target=$(awk '/^exec /{print $2; exit}' "$launcher" | tr -d "'")
  printf 'launcher: one you wrote by hand is at %s -- leaving it as is\n' "$launcher"
  printf '          it execs: %s\n' "${target:-nothing recognisable}"
  if [ -n "$target" ] && [ ! -x "$target" ]; then
    drift=1
    printf '          that target no longer exists -- rerun with --force to take it over\n'
  else
    printf '          rerun with --force to replace it with the generated one\n'
  fi
elif [ "$recorded" = "$repo" ]; then
  printf 'launcher: already installed for this checkout at %s\n' "$launcher"
elif [ -n "$recorded" ] && [ -d "$recorded" ]; then
  drift=1
  printf 'launcher: points at a different checkout, and both still exist\n'
  printf '          installed: %s\n' "$recorded"
  printf '          this one:  %s\n' "$repo"
  printf '          nothing was guessed -- rerun with --force to repoint it here\n'
else
  drift=1
  printf 'launcher: stale, generated for %s, which no longer exists\n' "${recorded:-no # repo: line}"
  if [ "$check_only" = 1 ]; then
    printf '          --check: would repoint it at %s\n' "$repo"
  else
    write_launcher
    printf '          repointed at %s\n' "$repo"
  fi
fi

# --- 3. the alias -----------------------------------------------------------
shell_name=""
if command -v dscl >/dev/null 2>&1; then
  shell_name=$(basename "$(dscl . -read "/Users/$USER" UserShell 2>/dev/null | awk '{print $2}')" 2>/dev/null || true)
fi
[ -n "$shell_name" ] || shell_name=$(basename "${SHELL:-sh}")
case "$shell_name" in
  zsh) rc="${MTPLX_RC:-$HOME/.zshrc}" ;;
  bash) rc="${MTPLX_RC:-$HOME/.bashrc}" ;;
  *) rc="${MTPLX_RC:-$HOME/.profile}" ;;
esac
printf 'login shell: %s -> %s\n' "$shell_name" "$rc"

# --- PATH: the entry must be IN FRONT, not merely present -------------------
# Three `mtplx` binaries exist on a machine like this one (repo, a Homebrew
# 2.7.1, the app runtime-venv). A line like PATH="$PATH:$HOME/.mtplx/bin" would
# satisfy "the dir is on PATH" and still lose to Homebrew, so the position is
# part of the check. Commented-out lines do not count.
path_needle=""
path_is_home=0
case "$bin_dir" in
  "$HOME"/*) path_needle="${bin_dir#"$HOME"/}"; path_is_home=1 ;;
  *) path_needle="$bin_dir"; path_is_home=0 ;;
esac
path_lineno=""
path_line=""
if [ -f "$rc" ]; then
  path_lineno=$(awk -v e="$path_needle" '
    { line=$0; sub(/^[ \t]+/, "", line) }
    substr(line, 1, 1) == "#" { next }
    index(line, "export PATH=") && index(line, e) { print NR; exit }
  ' "$rc")
fi
path_state=absent
path_owner=""
if [ -n "$path_lineno" ]; then
  path_line=$(awk -v n="$path_lineno" 'NR==n' "$rc")
  path_owner=$(awk -v n="$path_lineno" 'NR==n-1 && /^#/' "$rc")
  rest=${path_line#*"$path_needle"}
  case "$rest" in
    ':$PATH'*) path_state=front ;;
    *) path_state=behind ;;
  esac
fi

if [ "$path_is_home" = 1 ]; then
  path_want="export PATH=\"\$HOME/$path_needle:\$PATH\""
else
  path_want="export PATH=\"$bin_dir:\$PATH\""
fi

append_rc_line() {
  if ! grep -qF '# Added by scripts/install_repo_launcher.sh' "$rc"; then
    printf '\n# Added by scripts/install_repo_launcher.sh\n' >> "$rc"
  fi
  printf '%s\n' "$1" >> "$rc"
}

case "$path_state" in
  front)
    printf 'PATH: %s in front (%s:%s)\n' "$path_needle" "$rc" "$path_lineno"
    if [ -n "$path_owner" ]; then
      printf '      written by: %s\n' "$path_owner"
    fi
    ;;
  behind)
    drift=1
    printf 'PATH: %s is on PATH but NOT in front (%s:%s)\n' "$path_needle" "$rc" "$path_lineno"
    printf '      found: %s\n' "$path_line"
    printf '      something earlier on PATH can win `mtplx`; the front form gets added below\n'
    if [ "$check_only" = 0 ]; then
      append_rc_line "$path_want"
      printf 'PATH: added %s\n' "$path_want"
    fi
    ;;
  absent)
    drift=1
    if [ "$check_only" = 1 ]; then
      printf 'PATH: no %s entry in %s\n' "$path_needle" "$rc"
    else
      append_rc_line "$path_want"
      printf 'PATH: added %s\n' "$path_want"
    fi
    ;;
esac

# What the login shell actually runs is the only honest oracle: the rc text can be
# present and correct and still lose to an earlier PATH entry. Interactive startup
# prints banners (gitstatus alone emits 13 lines here), so take the last line that
# looks like an mtplx path, and never let a slow or hanging rc affect the result.
if [ "${MTPLX_NO_SHELL_PROBE:-0}" != 1 ]; then
  probe_bin="$shell_name"
  if [ -n "${MTPLX_LOGIN_SHELL:-}" ]; then
    probe_bin="$MTPLX_LOGIN_SHELL"
  fi
  if command -v "$probe_bin" >/dev/null 2>&1; then
    # `|| true`: under set -euo pipefail a pipeline whose grep finds nothing returns
    # 1, which would abort the whole script on an inconclusive probe.
    resolved=$(timeout 12 "$probe_bin" -lic 'command -v mtplx' 2>/dev/null | grep -E '/mtplx$' | tail -1) || true
    # zsh answers `command -v mtplx` with `alias mtplx=/path/to/mtplx` when an
    # alias exists; bash answers with the bare path. Compare the path, not the
    # shell's phrasing -- otherwise an installed alias, which is the normal
    # state after this script runs, reads as drift forever and `--check` can
    # never return 0. (Measured on the operator's zsh: the alias pointed at
    # exactly this launcher and the probe still said NOT.)
    case "$resolved" in
      alias\ *=*)
        resolved="${resolved#alias }"
        resolved="${resolved#*=}"
        ;;
    esac
    resolved="${resolved%\"}"; resolved="${resolved#\"}"
    resolved="${resolved%\'}"; resolved="${resolved#\'}"
    if [ -z "$resolved" ]; then
      printf 'shell probe: %s did not resolve `mtplx` (rc noise, timeout, or not on PATH)\n' "$shell_name"
    elif [ "$resolved" = "$launcher" ]; then
      printf 'shell probe: %s runs %s\n' "$shell_name" "$resolved"
    else
      drift=1
      printf 'shell probe: %s runs %s -- NOT %s\n' "$shell_name" "$resolved" "$launcher"
      printf '           a PATH entry ahead of this one wins, so the launcher above is not what you execute\n'
    fi
  fi
fi

if [ "$check_only" = 1 ]; then
  if grep -qE '^alias mtplx=' "$rc" 2>/dev/null; then
    echo "The alias already exists"
  else
    drift=1
    printf 'alias: missing from %s\n' "$rc"
  fi
else
  if [ ! -f "$rc" ] && ! touch -- "$rc" 2>/dev/null; then
    printf 'cannot write %s -- skipping the alias\n' "$rc" >&2
    exit 1
  fi
  if grep -qE '^alias mtplx=' "$rc"; then
    echo "The alias already exists"
    grep -nE '^alias mtplx=' "$rc" | head -1
  else
    append_rc_line "$alias_line"
    printf 'alias: added to %s\n' "$rc"
    printf 'activate it: source %s\n' "$rc"
  fi
fi

# --- 4. the measurement scripts: byte-identical copies + a sidecar manifest --
# The instruments behind docs/perf/receipts/qwen38-flash-next-prefill.md live in
# this checkout so they are versioned and reviewed. The operator's copies under
# $MTPLX_HOME/scripts are installed from there BYTE-IDENTICAL: no provenance
# header is injected into them, so `diff` against the checkout stays meaningful,
# and the provenance lives in a sidecar manifest instead. Three states per file,
# the same discipline as the launcher -- missing, behind (the checkout moved on,
# so updating it is ours to do), or foreign (edited by hand, so it is not ours to
# overwrite without --force).
#
# A checkout carrying none of them is NOT drift: this section is about the
# operator's copies, and a partial or unrelated checkout still installs a
# working launcher.
scripts_dir="${MTPLX_HOME:-$HOME/.mtplx}/scripts"
scripts_manifest="$scripts_dir/.repo-scripts.tsv"
repo_scripts=(
  prefill_probe.py
  prefill_lane_sweep.py
  followup_repeat.py
  suffix_width_sweep.py
  prefill_ladder_baseline.sh
)

blob_sha() { git -C "$repo" hash-object -- "$1" 2>/dev/null; }

manifest_sha() {
  [ -f "$scripts_manifest" ] || return 0
  awk -F '\t' -v n="$1" '$1 == n { print $2; exit }' "$scripts_manifest" 2>/dev/null
}

install_repo_scripts() {
  if ! command -v git >/dev/null 2>&1; then
    printf 'scripts: git is needed to compare the copies -- skipping\n'
    return 0
  fi
  local present=0 name
  for name in "${repo_scripts[@]}"; do
    [ -f "$repo/scripts/$name" ] && present=$((present + 1))
  done
  if [ "$present" = 0 ]; then
    printf 'scripts: this checkout carries none of the measurement scripts -- skipping\n'
    return 0
  fi
  if ! mkdir -p -- "$scripts_dir" 2>/dev/null; then
    printf 'scripts: cannot create %s -- skipping\n' "$scripts_dir" >&2
    drift=1
    return 0
  fi
  local tmp src dst src_sha dst_sha rec_sha
  tmp="$(mktemp)"
  for name in "${repo_scripts[@]}"; do
    src="$repo/scripts/$name"
    dst="$scripts_dir/$name"
    if [ ! -f "$src" ]; then
      printf 'scripts: %s is on the install list but not in the checkout\n' "$name" >&2
      drift=1
      continue
    fi
    src_sha="$(blob_sha "$src")"
    rec_sha="$(manifest_sha "$name")"
    if [ ! -f "$dst" ]; then
      drift=1
      if [ "$check_only" = 1 ]; then
        printf 'scripts: %s is not installed (--check: would install)\n' "$name"
      else
        cp -- "$src" "$dst" && chmod +x "$dst" 2>/dev/null
        printf 'scripts: installed %s\n' "$name"
      fi
    else
      dst_sha="$(blob_sha "$dst")"
      if [ "$dst_sha" = "$src_sha" ]; then
        printf 'scripts: %s up to date\n' "$name"
      elif [ -n "$rec_sha" ] && [ "$dst_sha" = "$rec_sha" ]; then
        drift=1
        if [ "$check_only" = 1 ]; then
          printf 'scripts: %s is behind the checkout (--check: would update)\n' "$name"
        else
          cp -- "$src" "$dst" && chmod +x "$dst" 2>/dev/null
          printf 'scripts: updated %s from the checkout\n' "$name"
        fi
      else
        drift=1
        printf 'scripts: %s differs from the checkout and was not installed by us\n' "$name"
        printf '         installed: %s\n' "$dst"
        printf '         checkout:  %s\n' "$src"
        if [ "$force" = 1 ] && [ "$check_only" != 1 ]; then
          cp -- "$src" "$dst" && chmod +x "$dst" 2>/dev/null
          printf '         --force: replaced with the checkout copy\n'
        else
          printf '         nothing overwritten -- rerun with --force to take it over\n'
        fi
      fi
    fi
    printf '%s\t%s\t%s\t%s\n' "$name" "$src_sha" "scripts/$name" \
      "$(date -u +%Y-%m-%dT%H:%M:%SZ)" >>"$tmp"
  done
  if [ "$check_only" != 1 ] && [ -s "$tmp" ]; then
    {
      printf '# measurement scripts installed by scripts/install_repo_launcher.sh\n'
      printf '# source checkout: %s\n' "$repo"
      printf '# name\tsha\trepo-path\tinstalled-at\n'
      cat -- "$tmp"
    } >"$scripts_manifest"
  fi
  rm -f -- "$tmp"
}

install_repo_scripts

# --- 5. the QSA sparse prefill lane: is the speed this checkout can serve on? --
# The long-context prefill win on M3-class GPUs comes from a vendored native
# extension (native_extensions/qsa_kernels) whose artifacts are GITIGNORED: a
# fresh clone, or a venv rebuilt by `uv sync`, silently falls back to dense QSA
# prefill and the 103 k cold prefill goes from ~105 s back to ~251 s. Nothing at
# boot says so -- the engine logs one line at first use and nobody reads it.
# So the guard lives here, where the rest of "is this checkout really serving"
# already lives.
#
# Inconclusive is NOT drift, same rule as the shell probe: a machine without a
# Metal toolchain cannot build the extension, and failing `--check` forever
# there would be noise, not a signal. Set MTPLX_NO_LANE_PROBE=1 to skip.
lane_buildable() {
  command -v cmake >/dev/null 2>&1 || return 1
  xcrun -sdk macosx metal --version >/dev/null 2>&1 || return 1
}

lane_build_recipe() {
  printf '         build it in the venv that serves:\n'
  printf '           uv pip install --python %s "nanobind==2.15.0" "setuptools>=42"\n' "$venv_python"
  printf '           (cd %s/native_extensions/qsa_kernels && %s setup.py build_ext --inplace)\n' "$repo" "$venv_python"
  printf '         nanobind is pinned exactly: a mismatch imports cleanly and then\n'
  printf '         rejects every mx.array (oMLX #2139). Rebuild after any mlx upgrade.\n'
}

if [ "${MTPLX_NO_LANE_PROBE:-0}" != 1 ]; then
  if [ ! -x "$venv_python" ]; then
    printf 'qsa lane: not probed, %s is missing\n' "$venv_python"
  else
    # One line, one token, so a noisy import cannot be mistaken for an answer.
    lane_answer=$(timeout 180 "$venv_python" -P -c '
import json
out = {"state": "UNKNOWN"}
try:
    import mlx.core as mx
    if not mx.metal.is_available():
        out = {"state": "UNSUPPORTED", "detail": "metal unavailable"}
    else:
        from mtplx.kernels import qsa_prefill_direct as d
        err = getattr(d, "_IMPORT_ERROR", None)
        if err is not None:
            # Flat, quote-free detail: the shell side reads it with one sed, and
            # nested JSON would be truncated at the first escaped quote.
            out = {"state": "MISSING_EXT", "detail": str(err).replace(chr(34), "")}
        else:
            info = d.qsa_prefill_direct_build_info()
            built = str(info.get("built_against_mlx"))
            imported = str(info.get("imported_mlx"))
            if built != imported:
                out = {
                    "state": "MISMATCH",
                    "detail": "built_against_mlx=%s imported_mlx=%s" % (built, imported),
                }
            else:
                from mtplx.models.qwen4_exp import qsa_prefill_lane_auto_supported
                out = {
                    "state": "OK" if qsa_prefill_lane_auto_supported() else "UNSUPPORTED",
                    "detail": "mlx %s, nanobind %s" % (imported, info.get("built_against_nanobind")),
                }
except Exception as exc:
    out = {"state": "PROBE_FAILED", "detail": "%s: %s" % (type(exc).__name__, exc)}
print("MTPLX_LANE_PROBE " + json.dumps(out, sort_keys=True))
' 2>/dev/null | grep '^MTPLX_LANE_PROBE ' | tail -1 | sed 's/^MTPLX_LANE_PROBE //') || true
    lane_state=""
    lane_detail=""
    if [ -n "$lane_answer" ]; then
      lane_state=$(printf '%s' "$lane_answer" | sed -n 's/.*"state": *"\([A-Z_]*\)".*/\1/p')
      lane_detail=$(printf '%s' "$lane_answer" | sed -n 's/.*"detail": *"\([^"]*\)".*/\1/p')
    fi
    case "$lane_state" in
      OK)
        printf 'qsa lane: sparse prefill available (%s)\n' "${lane_detail:-receipts ok}"
        ;;
      MISSING_EXT|MISMATCH)
        printf 'qsa lane: %s -- dense QSA prefill, the slow curve\n' "$lane_state"
        [ -n "$lane_detail" ] && printf '         %s\n' "$lane_detail"
        if lane_buildable; then
          drift=1
          printf '         this machine can build it (cmake + xcrun metal), so this is actionable\n'
          lane_build_recipe
          if [ "$check_only" != 1 ]; then
            printf '         not built for you: a native compile is not an install step\n'
          fi
        else
          printf '         no cmake or no `xcrun -sdk macosx metal` here, so this is not\n'
          printf '         actionable on this machine -- reported, not counted as drift\n'
        fi
        ;;
      UNSUPPORTED)
        printf 'qsa lane: not available on this machine (%s)\n' "${lane_detail:-no fast consumer}"
        ;;
      PROBE_FAILED)
        printf 'qsa lane: probe failed (%s) -- inconclusive, not drift\n' "${lane_detail:-unknown}"
        ;;
      *)
        printf 'qsa lane: did not answer (timeout or import noise) -- inconclusive, not drift\n'
        ;;
    esac
  fi
else
  printf 'qsa lane: probe skipped (MTPLX_NO_LANE_PROBE=1)\n'
fi

if [ "$check_only" = 1 ]; then
  if [ "$drift" = 1 ]; then
    printf '\n--check: drift found, nothing written\n'
    exit 1
  fi
  printf '\n--check: aligned, nothing written\n'
  exit 0
fi

printf '\nverify: %s status | head -3   (python: should be %s)\n' "$launcher" "$venv_python"
